apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: monitor
data:
  mode: "http"  # 可选值: "http" 或 "db"
  host: "mysql-service"
  port: "3306"
  user: "your-user"
  password: "your-password"
  database: "metrics_db"
  interval: "30s"  # 支持的格式：30s, 1m, 1h 等
  reserve_mem: "1024"  # 保留内存值，单位为MB
