apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-collector
  namespace: monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-collector-role
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-collector-binding
subjects:
- kind: ServiceAccount
  name: metrics-collector
  namespace: monitor
roleRef:
  kind: ClusterRole
  name: metrics-collector-role
  apiGroup: rbac.authorization.k8s.io 
