apiVersion: v1
kind: Service
metadata:
  name: metrics-collector-svc
  namespace: monitor
spec:
  selector:
    app: metrics-collector
  ports:
    - protocol: TCP
      port: 38080
      targetPort: 8080
  type: ClusterIP 